# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[fuzzers/CiffParserFuzzer-GetDecoder]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/CiffParserFuzzer-GetDecoder" "-help=1")
set_tests_properties([=[fuzzers/CiffParserFuzzer-GetDecoder]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;29;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/CiffParserFuzzer-GetDecoder-Decode]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/CiffParserFuzzer-GetDecoder-Decode" "-help=1")
set_tests_properties([=[fuzzers/CiffParserFuzzer-GetDecoder-Decode]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;30;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/FiffParserFuzzer-GetDecoder]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/FiffParserFuzzer-GetDecoder" "-help=1")
set_tests_properties([=[fuzzers/FiffParserFuzzer-GetDecoder]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;29;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/FiffParserFuzzer-GetDecoder-Decode]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/FiffParserFuzzer-GetDecoder-Decode" "-help=1")
set_tests_properties([=[fuzzers/FiffParserFuzzer-GetDecoder-Decode]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;30;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/RawParserFuzzer-GetDecoder]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/RawParserFuzzer-GetDecoder" "-help=1")
set_tests_properties([=[fuzzers/RawParserFuzzer-GetDecoder]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;29;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/RawParserFuzzer-GetDecoder-Decode]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/RawParserFuzzer-GetDecoder-Decode" "-help=1")
set_tests_properties([=[fuzzers/RawParserFuzzer-GetDecoder-Decode]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;30;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/TiffParserFuzzer-GetDecoder]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/TiffParserFuzzer-GetDecoder" "-help=1")
set_tests_properties([=[fuzzers/TiffParserFuzzer-GetDecoder]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;29;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
add_test([=[fuzzers/TiffParserFuzzer-GetDecoder-Decode]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/fuzz/librawspeed/parsers/TiffParserFuzzer-GetDecoder-Decode" "-help=1")
set_tests_properties([=[fuzzers/TiffParserFuzzer-GetDecoder-Decode]=] PROPERTIES  LABELS "fuzz;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;31;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/CMakeLists.txt;43;add_fuzz_target__base;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;14;add_fuzz_target;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;30;add_parser_fuzzer;/Users/fuguoqiang/Desktop/bridge/rawspeed/fuzz/librawspeed/parsers/CMakeLists.txt;0;")
