# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[BitTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/BitTest")
set_tests_properties([=[BitTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[CoalescingOutputIteratorTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/CoalescingOutputIteratorTest")
set_tests_properties([=[CoalescingOutputIteratorTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[NORangesSetTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/NORangesSetTest")
set_tests_properties([=[NORangesSetTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[PartitioningOutputIteratorTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/PartitioningOutputIteratorTest")
set_tests_properties([=[PartitioningOutputIteratorTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[PointTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/PointTest")
set_tests_properties([=[PointTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[RangeTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/RangeTest")
set_tests_properties([=[RangeTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[VariableLengthLoadTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/adt/VariableLengthLoadTest")
set_tests_properties([=[VariableLengthLoadTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;12;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/adt/CMakeLists.txt;0;")
