# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[BayerPhaseTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/common/BayerPhaseTest")
set_tests_properties([=[BayerPhaseTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;0;")
add_test([=[ChecksumFileTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/common/ChecksumFileTest")
set_tests_properties([=[ChecksumFileTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;0;")
add_test([=[CommonTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/common/CommonTest")
set_tests_properties([=[CommonTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;0;")
add_test([=[CpuidTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/common/CpuidTest")
set_tests_properties([=[CpuidTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;0;")
add_test([=[SplineTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/common/SplineTest")
set_tests_properties([=[SplineTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/common/CMakeLists.txt;0;")
