# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/metadata
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[BlackAreaTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/metadata/BlackAreaTest")
set_tests_properties([=[BlackAreaTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;0;")
add_test([=[CameraMetaDataTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/metadata/CameraMetaDataTest")
set_tests_properties([=[CameraMetaDataTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;0;")
add_test([=[CameraSensorInfoTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/metadata/CameraSensorInfoTest")
set_tests_properties([=[CameraSensorInfoTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;0;")
add_test([=[CameraTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/metadata/CameraTest")
set_tests_properties([=[CameraTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;0;")
add_test([=[ColorFilterArrayTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/metadata/ColorFilterArrayTest")
set_tests_properties([=[ColorFilterArrayTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;10;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/metadata/CMakeLists.txt;0;")
