# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[BitStreamerBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitStreamerBenchmark" "--help")
set_tests_properties([=[BitStreamerBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitStreamerBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitStreamerBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[BitStreamerBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitStreamerJPEGBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitStreamerJPEGBenchmark" "--help")
set_tests_properties([=[BitStreamerJPEGBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitStreamerJPEGBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitStreamerJPEGBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[BitStreamerJPEGBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitVacuumerBenchmark" "--help")
set_tests_properties([=[BitVacuumerBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitVacuumerBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[BitVacuumerBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerJPEGBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitVacuumerJPEGBenchmark" "--help")
set_tests_properties([=[BitVacuumerJPEGBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerJPEGBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/bitstreams/BitVacuumerJPEGBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[BitVacuumerJPEGBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;19;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/bitstreams/CMakeLists.txt;0;")
