# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[BitStreamerJPEGTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitStreamerJPEGTest")
set_tests_properties([=[BitStreamerJPEGTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitStreamerLSBTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitStreamerLSBTest")
set_tests_properties([=[BitStreamerLSBTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitStreamerMSB16Test]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitStreamerMSB16Test")
set_tests_properties([=[BitStreamerMSB16Test]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitStreamerMSB32Test]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitStreamerMSB32Test")
set_tests_properties([=[BitStreamerMSB32Test]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerJPEGTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitVacuumerJPEGTest")
set_tests_properties([=[BitVacuumerJPEGTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerLSBTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitVacuumerLSBTest")
set_tests_properties([=[BitVacuumerLSBTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerMSB16Test]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitVacuumerMSB16Test")
set_tests_properties([=[BitVacuumerMSB16Test]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerMSB32Test]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitVacuumerMSB32Test")
set_tests_properties([=[BitVacuumerMSB32Test]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
add_test([=[BitVacuumerMSBTest]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed/bitstreams/BitVacuumerMSBTest")
set_tests_properties([=[BitVacuumerMSBTest]=] PROPERTIES  LABELS "unittest" WORKING_DIRECTORY "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/test/librawspeed" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/CMakeLists.txt;17;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;15;add_rs_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/test/librawspeed/bitstreams/CMakeLists.txt;0;")
