# CMake generated Testfile for 
# Source directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt
# Build directory: /Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CoalescingOutputIteratorBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt/CoalescingOutputIteratorBenchmark" "--help")
set_tests_properties([=[CoalescingOutputIteratorBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;8;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[CoalescingOutputIteratorBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt/CoalescingOutputIteratorBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[CoalescingOutputIteratorBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;8;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[DefaultInitAllocatorAdaptorBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt/DefaultInitAllocatorAdaptorBenchmark" "--help")
set_tests_properties([=[DefaultInitAllocatorAdaptorBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;8;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[DefaultInitAllocatorAdaptorBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt/DefaultInitAllocatorAdaptorBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[DefaultInitAllocatorAdaptorBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;8;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[VariableLengthLoadBenchmark-Dummy]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt/VariableLengthLoadBenchmark" "--help")
set_tests_properties([=[VariableLengthLoadBenchmark-Dummy]=] PROPERTIES  LABELS "benchmark;dummy" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;18;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;8;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;0;")
add_test([=[VariableLengthLoadBenchmark]=] "/Users/fuguoqiang/Desktop/bridge/rawspeed/test-cross-compile/build-aarch64-apple-darwin/bench/librawspeed/adt/VariableLengthLoadBenchmark" "--benchmark_min_time=1x")
set_tests_properties([=[VariableLengthLoadBenchmark]=] PROPERTIES  ENVIRONMENT "RAWSPEED_BENCHMARK_DRYRUN=1" LABELS "benchmark" _BACKTRACE_TRIPLES "/Users/fuguoqiang/Desktop/bridge/rawspeed/cmake/cmake-command-wrappers.cmake;19;add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/CMakeLists.txt;24;rawspeed_add_test;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;8;add_rs_bench;/Users/fuguoqiang/Desktop/bridge/rawspeed/bench/librawspeed/adt/CMakeLists.txt;0;")
